name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build & Package
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Run Build Script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Run Package Script
        run: |
          chmod +x package.sh
          ./package.sh

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          files: ChargeControl.dmg
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
